name: Docker Publish

on:
  push:
    branches:
      - main



jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: sdc
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 19981024tyz
        ports:
          - "5432:5432"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tanyunzhe/sdc-review:latest

      - name: SSH to EC2 instance and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-135-221-34.us-east-2.compute.amazonaws.com
          username: ubuntu
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            docker pull tanyunzhe/sdc-review:latest
            docker run -p 3000:80 --env-file env.list tanyunzhe/sdc-review:latest